(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{},U=function(){return Screens.util};
  Screens.actions=function(c){
    var S=c.S,UI=c.UI,VM=c.VM,esc=c.esc,tag=c.tag,f=c.filters||{},all=c.visibleActions();
    var owners=Array.from(new Set(all.map(function(a){return a.owner}).filter(Boolean))).sort();
    var acts=all.filter(function(a){var q=String(f.actionQuery||"").trim().toLowerCase();if(f.actionStatusFilter&&f.actionStatusFilter!=="all"&&a.status!==f.actionStatusFilter)return false;if(f.actionOwnerFilter&&f.actionOwnerFilter!=="all"&&a.owner!==f.actionOwnerFilter)return false;return !q||[a.text,a.owner,a.due,a.status,a.actionType].filter(Boolean).join(" ").toLowerCase().includes(q)});
    var vm=VM.actionSummary?VM.actionSummary(all,c.daysUntil,c.actionEvidenceCount):{total:0,open:0,overdue:0,pendingVerification:0,closed:0,withClosureEvidence:0};
    var buckets={overdue:0,due_7:0,due_30:0,later:0,no_due:0};all.filter(function(a){return a.status!=="closed"}).forEach(function(a){buckets[U().aging(c.daysUntil(a.due)).bucket]++});
    var hero=UI.pageIntro({eyebrow:"REMEDIATION & VERIFICATION",title:"Khắc phục & xác minh",description:"Theo dõi tuổi hành động, hạn xử lý, bằng chứng đóng và xác minh độc lập. Action Owner không được tự xác minh."});
    var summary=UI.metricGrid([{label:"Tổng hành động",value:vm.total,tone:"info"},{label:"Đang mở",value:vm.open,tone:"warning"},{label:"Quá hạn",value:vm.overdue,tone:vm.overdue?"danger":"positive"},{label:"Chờ xác minh",value:vm.pendingVerification,tone:"warning"},{label:"Đã đóng",value:vm.closed,tone:"positive"},{label:"Có bằng chứng đóng",value:vm.withClosureEvidence,tone:"neutral"}]);
    var aging='<div class="aging-strip"><div class="aging-cell danger"><b>'+buckets.overdue+'</b><span>Quá hạn</span></div><div class="aging-cell warning"><b>'+buckets.due_7+'</b><span>≤ 7 ngày</span></div><div class="aging-cell info"><b>'+buckets.due_30+'</b><span>8–30 ngày</span></div><div class="aging-cell"><b>'+buckets.later+'</b><span>&gt; 30 ngày</span></div><div class="aging-cell"><b>'+buckets.no_due+'</b><span>Chưa có hạn</span></div></div>';
    function actionEvidenceDetails(aid){
      return (S.links||[]).filter(function(l){return l.targetType==="RemediationAction"&&l.targetId===aid}).map(function(l){
        var rv=(S.revisions||[]).find(function(x){return x.id===l.revId}),ev=rv&&(S.evidence||[]).find(function(x){return x.id===rv.evidenceId});
        return rv&&ev?{link:l,revision:rv,evidence:ev}:null;
      }).filter(Boolean);
    }
    var controls='<div class="row product-toolbar" style="margin-bottom:12px"><input id="actionSearch" value="'+esc(f.actionQuery||"")+'" placeholder="Tìm hành động..." style="min-width:250px"><select id="actionStatusFilter"><option value="all">Tất cả trạng thái</option>'+Array.from(new Set(S.actions.map(function(a){return a.status}))).map(function(s){return'<option value="'+esc(s)+'" '+(f.actionStatusFilter===s?"selected":"")+'>'+esc(c.lab(s))+'</option>'}).join("")+'</select><select id="actionOwnerFilter"><option value="all">Tất cả người phụ trách</option>'+owners.map(function(o){return'<option value="'+esc(o)+'" '+(f.actionOwnerFilter===o?"selected":"")+'>'+esc(o)+'</option>'}).join("")+'</select><span class="small muted">'+acts.length+' kết quả</span></div>';
    var table=acts.length?'<div class="table"><table><thead><tr><th>Hành động</th><th>Loại</th><th>Người phụ trách</th><th>Tuổi hành động</th><th>Hạn / Aging</th><th>Bằng chứng đóng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>'+acts.map(function(a){var evs=actionEvidenceDetails(a.id),n=evs.length,canSubmit=c.canUpdateAction(a)&&a.status!=="closed",canVerify=a.status==="submitted_for_verification"&&n>0&&c.can("verify_action")&&a.ownerPersonaId!==c.ComplianceAccess.current().id,age=c.daysFrom(a.createdAt),aging=U().aging(c.daysUntil(a.due));return'<tr><td><b>'+esc(a.text)+'</b></td><td>'+(a.actionType==="mandatory_remediation"?'<span class="tag red">Khắc phục bắt buộc</span>':'<span class="tag blue">Cải thiện</span>')+'</td><td>'+esc(a.owner)+'</td><td>'+(age===null?"—":age+" ngày")+'</td><td>'+esc(a.due||"—")+'<div class="aging-pill '+aging.tone+'">'+esc(aging.label)+'</div></td><td><b>'+n+'</b> tệp'+(a.closureSubmittedAt?'<div class="small muted">Nộp: '+U().fmtDate(a.closureSubmittedAt)+'</div>':"")+(evs.length?'<div class="closure-evidence-list">'+evs.map(function(x){return'<div class="closure-evidence-item"><span>'+esc(x.evidence.name)+'</span>'+(x.revision.fileUri?'<span><button class="btn alt" data-evidence-preview="'+x.revision.id+'">Xem</button><button class="btn alt" data-evidence-download="'+x.revision.id+'">Tải</button></span>':'')+'</div>'}).join("")+'</div>':'')+'</td><td>'+tag(a.status)+'</td><td>'+(canSubmit?'<button class="btn alt" data-action-evidence="'+a.id+'">Nộp bằng chứng</button>':"")+(canVerify?'<button class="btn" data-verify="'+a.id+'">Xác minh</button>':a.ownerPersonaId===c.ComplianceAccess.current().id&&a.status==="submitted_for_verification"?'<div class="small muted">Không tự xác minh</div>':a.status!=="closed"&&n===0?'<div class="small muted">Cần bằng chứng đóng</div>':"")+'</td></tr>'}).join("")+'</tbody></table></div>':UI.empty("Chưa có hành động phù hợp","Hành động xuất hiện sau khi Phát hiện được chốt và giao xử lý.");
    return hero+summary+aging+controls+table;
  };
})();