(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{};
  Screens.assessments=function(c){
    var S=c.S,UI=c.UI,VM=c.VM,esc=c.esc,tag=c.tag,lab=c.lab,f=c.filters||{};
    var rows=c.visibleAssessments().filter(function(a){var u=S.org.find(function(x){return x.id===a.orgId}),q=String(f.assessmentQuery||"").trim().toLowerCase();if(f.assessmentStatusFilter&&f.assessmentStatusFilter!=="all"&&a.status!==f.assessmentStatusFilter)return false;if(f.assessmentOrgFilter&&f.assessmentOrgFilter!=="all"&&a.orgId!==f.assessmentOrgFilter)return false;return !q||[a.name,a.objective,a.processRef,a.activityRef,a.locationRef,a.leadAssessor,a.reviewer,u&&u.name].filter(Boolean).join(" ").toLowerCase().includes(q)});
    var all=c.visibleAssessments(),vm=VM.assessmentSummary?VM.assessmentSummary(all,c.visibleRA()):{open:0,fieldwork:0,review:0,closed:0,coverage:0,totalPoints:0,donePoints:0,orgCount:0};
    var hero=UI.pageIntro({eyebrow:"ASSESSMENT PLANNING",title:"Chương trình đánh giá",description:"Phạm vi = Đơn vị + Quy trình + Hoạt động + Địa điểm; hệ thống tự xác định Yêu cầu tuân thủ phù hợp.",actions:c.can("manage_assessment")?'<button class="btn" data-act="newas">+ Tạo đánh giá</button>':""});
    var metrics=UI.metricGrid([{label:"Đánh giá đang mở",value:vm.open,tone:"info"},{label:"Đang kiểm tra",value:vm.fieldwork,tone:"warning"},{label:"Đang rà soát",value:vm.review,tone:"warning"},{label:"Đã đóng",value:vm.closed,tone:"positive"},{label:"Coverage tổng",value:vm.coverage+"%",tone:"positive",meta:vm.donePoints+"/"+vm.totalPoints+" điểm hoàn tất"},{label:"Đơn vị có đánh giá",value:vm.orgCount,tone:"neutral"}]);
    var controls='<div class="row product-toolbar" style="margin:12px 0"><input id="assessmentSearch" value="'+esc(f.assessmentQuery||"")+'" placeholder="Tìm cuộc đánh giá..." style="min-width:250px"><select id="assessmentStatusFilter"><option value="all">Tất cả trạng thái</option>'+Array.from(new Set(S.assessments.map(function(a){return a.status}))).map(function(s){return'<option value="'+esc(s)+'" '+(f.assessmentStatusFilter===s?"selected":"")+'>'+esc(lab(s))+'</option>'}).join("")+'</select><select id="assessmentOrgFilter"><option value="all">Tất cả đơn vị</option>'+S.org.map(function(u){return'<option value="'+u.id+'" '+(f.assessmentOrgFilter===u.id?"selected":"")+'>'+esc(u.name)+'</option>'}).join("")+'</select><span class="small muted">'+rows.length+' kết quả</span></div>';
    var table=rows.length?'<div class="table"><table><thead><tr><th>Tên</th><th>Đơn vị</th><th>Phạm vi</th><th>Thời kỳ</th><th>Yêu cầu</th><th>Tiến độ</th><th>Trạng thái</th><th>Điều khiển</th></tr></thead><tbody>'+rows.map(function(a){var u=S.org.find(function(x){return x.id===a.orgId}),ras=S.ra.filter(function(x){return x.assessmentId===a.id}),d=ras.filter(function(x){return x.workflow==="done"&&x.result!=="not_assessed"}).length,p=ras.length?Math.round(d*100/ras.length):0,scope=[a.processRef,a.activityRef,a.locationRef].filter(Boolean).join(" · ")||"Toàn bộ phạm vi áp dụng",pendingFindings=S.findings.filter(function(f){var r=S.ra.find(function(x){return x.id===f.raId});return r&&r.assessmentId===a.id&&["draft","pending_unit_response","pending_final_review"].includes(f.status)}).length,missingMandatory=S.findings.filter(function(f){var r=S.ra.find(function(x){return x.id===f.raId});return r&&r.assessmentId===a.id&&f.status==="final"&&f.remediationRequired&&!S.actions.some(function(x){return x.findingId===f.id&&x.actionType==="mandatory_remediation"})}).length,buttons='<button class="btn alt" data-open="'+a.id+'">Mở workspace</button>';if(a.status==="draft"&&c.can("manage_assessment",a))buttons+='<button class="btn" data-assessment-start="'+a.id+'">Bắt đầu kiểm tra</button>';if(a.status==="fieldwork"&&(c.can("manage_assessment",a)||c.can("conduct_fieldwork",a)))buttons+='<button class="btn" data-assessment-review="'+a.id+'" '+((d!==ras.length||pendingFindings>0||missingMandatory>0)?"disabled":"")+'>Gửi rà soát</button>';if(a.status==="review"&&c.can("review_assessment",a))buttons+='<button class="btn" data-assessment-close="'+a.id+'">Đóng đánh giá</button>';return'<tr><td><b>'+esc(a.name)+'</b><div class="small muted">'+esc(a.objective||"")+'</div><div class="small muted">Trưởng đoàn: '+esc(a.leadAssessor||"—")+' · Rà soát: '+esc(a.reviewer||"—")+'</div></td><td>'+esc(u&&u.name)+'</td><td>'+esc(scope)+(a.lockedAt?'<div class="small muted">🔒 Phạm vi đã khóa</div>':"")+'</td><td>'+esc((a.periodFrom||"—")+" → "+(a.periodTo||"—"))+'</td><td>'+ras.length+'</td><td>'+UI.progress(p,d+"/"+ras.length)+(pendingFindings?'<div class="small muted">'+pendingFindings+' phát hiện đang chờ xử lý</div>':"")+(missingMandatory?'<div class="small muted">'+missingMandatory+' yêu cầu khắc phục chưa có hành động bắt buộc</div>':"")+'</td><td>'+tag(a.status)+'</td><td><div class="row">'+buttons+'</div></td></tr>'}).join("")+'</tbody></table></div>':UI.empty("Chưa có cuộc đánh giá phù hợp","Điều chỉnh bộ lọc hoặc tạo đánh giá mới.");
    return hero+metrics+controls+table;
  };
})();