(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{};
  Screens.dashboard=function(c){
    var S=c.S,UI=c.UI,esc=c.esc,tag=c.tag,m=c.metrics(),fs=c.visibleFindings(),acts=c.visibleActions();
    var high=fs.filter(function(f){return f.status!=="closed"&&f.status!=="dismissed"&&(f.severity==="high"||f.severity==="critical")}).length;
    var pendingResp=fs.filter(function(f){return f.status==="pending_unit_response"}).length;
    var pendingFinal=fs.filter(function(f){return f.status==="pending_final_review"}).length;
    var pendingVerify=acts.filter(function(a){return a.status==="submitted_for_verification"}).length;
    var reqCount={};fs.filter(function(f){return f.status==="final"||f.status==="closed"}).forEach(function(f){var ra=S.ra.find(function(r){return r.id===f.raId});if(ra)reqCount[ra.requirementId]=(reqCount[ra.requirementId]||0)+1});
    var repeat=Object.values(reqCount).filter(function(n){return n>1}).length;
    var sourceAttention=S.sources.filter(function(s){return s.status==="pending_approval"||s.status==="needs_ocr"||s.status==="error"}).length;
    var alerts=c.syncNotifications().slice().sort(function(a,b){var rank={critical:0,warning:1,info:2};return rank[a.level]-rank[b.level]}).slice(0,8);
    var orgRows=S.org.map(function(u){var aids=c.visibleAssessments().filter(function(a){return a.orgId===u.id}).map(function(a){return a.id});var fids=fs.filter(function(f){var ra=S.ra.find(function(r){return r.id===f.raId});return ra&&aids.indexOf(ra.assessmentId)>=0});var fa=fids.map(function(f){return f.id});var aa=acts.filter(function(a){return fa.indexOf(a.findingId)>=0});return{name:u.name,find:fids.filter(function(f){return f.status!=="closed"&&f.status!=="dismissed"}).length,over:aa.filter(function(a){var d=c.daysUntil(a.due);return a.status!=="closed"&&d!==null&&d<0}).length}}).filter(function(x){return x.find||x.over});
    var hero=UI.pageIntro({eyebrow:"COMPLIANCE CONTROL TOWER",title:"Điều hành tuân thủ",description:"Theo dõi tiến độ đánh giá, phát hiện, khắc phục và điểm cần chuyển cấp theo đúng phạm vi được phân quyền.",actions:'<button class="btn alt" data-act="notifications">Điểm cần xử lý</button>'});
    var kpis=UI.metricGrid([{label:"Cuộc đánh giá đang mở",value:m.active,tone:"info",meta:"Theo phạm vi hiện tại"},{label:"Coverage",value:m.coverage+"%",tone:"positive",meta:"Điểm đã hoàn tất đánh giá"},{label:"Phát hiện đang mở",value:m.find,tone:m.find?"warning":"positive"},{label:"Mức cao / nghiêm trọng",value:high,tone:high?"danger":"positive"},{label:"Hành động quá hạn",value:m.over,tone:m.over?"danger":"positive"},{label:"Chờ xác minh",value:pendingVerify,tone:pendingVerify?"warning":"neutral"}]);
    var pipeline='<div class="insight-grid"><div class="insight"><span class="small muted">Chờ đơn vị phản hồi</span><b>'+pendingResp+'</b></div><div class="insight"><span class="small muted">Chờ chốt sau phản hồi</span><b>'+pendingFinal+'</b></div><div class="insight"><span class="small muted">Yêu cầu có phát hiện lặp lại</span><b>'+repeat+'</b></div><div class="insight"><span class="small muted">Nguồn cần xử lý</span><b>'+sourceAttention+'</b></div></div>';
    var alertBody=alerts.length?alerts.map(function(n){return'<div class="alert-item '+n.level+'"><span class="tag '+(n.level==="critical"?"red":n.level==="warning"?"amber":"blue")+'">'+esc(n.type)+'</span><b style="display:block;margin-top:5px">'+esc(n.title)+'</b><div class="small muted">'+esc(n.text)+'</div></div>'}).join(""):UI.empty("Không có cảnh báo cần xử lý","Các cảnh báo mới sẽ xuất hiện theo vai trò và phạm vi đơn vị.");
    var orgBody=orgRows.length?'<div class="table"><table><thead><tr><th>Đơn vị</th><th>Phát hiện mở</th><th>Hành động quá hạn</th></tr></thead><tbody>'+orgRows.map(function(x){return'<tr><td><b>'+esc(x.name)+'</b></td><td>'+x.find+'</td><td>'+x.over+'</td></tr>'}).join("")+'</tbody></table></div>':UI.empty("Chưa có vấn đề theo đơn vị","Không có phát hiện mở hoặc hành động quá hạn trong phạm vi hiện tại.");
    var progress=c.visibleAssessments().map(function(a){var rows=S.ra.filter(function(r){return r.assessmentId===a.id}),done=rows.filter(function(r){return r.workflow==="done"}).length,p=rows.length?Math.round(done*100/rows.length):0;return'<div class="assessment-progress"><div class="row"><div><b>'+esc(a.name)+'</b><div class="small muted">'+done+'/'+rows.length+' điểm hoàn tất</div></div><span class="right">'+tag(a.status)+'</span></div>'+UI.progress(p,"Tiến độ")+'</div>'}).join("");
    return hero+kpis+pipeline+'<div class="split" style="margin-top:16px"><div class="card">'+UI.sectionHeader("Điểm cần xử lý","Ưu tiên theo mức độ và workflow",'<button class="btn alt" data-act="notifications">Xem tất cả</button>')+'<div class="alert-list">'+alertBody+'</div></div><div class="card">'+UI.sectionHeader("Tình hình theo đơn vị","Chỉ hiển thị phạm vi được phép xem","")+orgBody+'</div></div><div class="card" style="margin-top:16px">'+UI.sectionHeader("Tiến độ chương trình đánh giá","Coverage theo từng cuộc đánh giá","")+(progress||UI.empty("Chưa có cuộc đánh giá","Tạo chương trình đánh giá để bắt đầu."))+'</div>';
  };
})();