(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{},U=function(){return Screens.util};
  function evidenceCards(c,ra){
    var S=c.S,esc=c.esc,links=S.links.filter(function(l){return l.targetId===ra.id&&l.targetType==="RequirementAssessment"});
    if(!links.length)return c.UI.empty("Chưa có bằng chứng","Upload ảnh, PDF, chứng từ hoặc screenshot để hình thành hồ sơ bằng chứng.");
    return'<div class="evidence-grid">'+links.map(function(l){var rv=S.revisions.find(function(x){return x.id===l.revId}),ev=rv&&S.evidence.find(function(x){return x.id===rv.evidenceId});if(!ev||!rv)return"";return'<article class="evidence-card"><div class="evidence-type">'+esc((rv.mime||ev.type||"file").split("/").pop().toUpperCase())+'</div><div class="evidence-body"><b>'+esc(ev.name)+'</b><div class="small muted">v'+esc(rv.version)+' · '+U().formatBytes(rv.size||rv.fileSize)+' · '+U().fmtDate(rv.capturedAt)+'</div><div class="small muted">Storage: '+esc(ev.storage||rv.storageProvider||"private")+(l.purpose?" · "+esc(l.purpose):"")+'</div>'+(rv.fileUri?'<div class="row evidence-actions"><button class="btn alt" data-evidence-preview="'+rv.id+'">Xem</button><button class="btn alt" data-evidence-download="'+rv.id+'">Tải xuống</button></div>':'<div class="small muted">Bản demo chỉ có metadata; chưa có tệp vật lý.</div>')+'</div></article>'}).join("")+'</div>';
  }
  Screens.fieldwork=function(c){
    var S=c.S,UI=c.UI,esc=c.esc,tag=c.tag,state=c.selection;
    var a=c.visibleAssessments().find(function(x){return x.id===state.selectedAssessment})||c.visibleAssessments()[0];
    var hero=UI.pageIntro({eyebrow:"FIELDWORK & EVIDENCE",title:"Kiểm tra hiện trường",description:"Đối chiếu từng Yêu cầu tuân thủ với dữ kiện và bằng chứng. AI chỉ đề xuất; kết quả chính thức do người kiểm tra xác nhận."});
    if(!a)return hero+UI.empty("Chưa có cuộc đánh giá","Tạo chương trình đánh giá trước khi thực hiện fieldwork.");
    c.setSelection("selectedAssessment",a.id);
    var rows=S.ra.filter(function(x){return x.assessmentId===a.id});
    if(!rows.some(function(x){return x.id===state.selectedRA}))c.setSelection("selectedRA",rows[0]&&rows[0].id);
    var selected=c.getSelection("selectedRA"),ra=rows.find(function(x){return x.id===selected}),rq=ra&&S.requirements.find(function(x){return x.id===ra.requirementId}),props=ra?S.proposals.filter(function(p){return p.raId===ra.id}).slice().reverse():[],fieldworkActive=a.status==="fieldwork",me=c.ComplianceAccess.current(),assignment=ra&&(S.requirementAssignments||[]).find(function(x){return x.raId===ra.id&&x.assignmentRole==="primary_assessor"&&x.status==="active"}),canWork=fieldworkActive&&Boolean(ra)&&(c.can("assign_assessment_work",a)||assignment&&assignment.userId===me.id);
    var left=rows.map(function(r){var q=S.requirements.find(function(x){return x.id===r.requirementId}),as=(S.requirementAssignments||[]).find(function(x){return x.raId===r.id&&x.assignmentRole==="primary_assessor"&&x.status==="active"}),mine=as&&as.userId===me.id;return'<div class="req '+(r.id===selected?"on ":"")+(mine?"assigned-me":"")+'" data-ra="'+r.id+'"><div class="row"><div><b>'+esc(q.code)+' · '+esc(q.title)+'</b><div class="small muted">'+esc(q.expected)+'</div><div class="small muted">Người kiểm tra: '+esc(as?as.displayName:"Chưa phân công")+(mine?" · Việc của tôi":"")+'</div></div><span class="right">'+tag(r.result)+' '+tag(r.workflow)+'</span></div></div>'}).join("");
    var right=ra?'<div class="card fieldwork-detail"><div class="row"><div><h2>'+esc(rq.code)+' · '+esc(rq.title)+'</h2><p>'+esc(rq.description)+'</p><div class="small muted"><b>Người kiểm tra chính:</b> '+esc(assignment?assignment.displayName:"Chưa phân công")+'</div></div><span class="right">'+tag(ra.result)+'</span></div>'+(fieldworkActive&&!canWork?'<div class="note"><b>Chỉ xem.</b> Yêu cầu này được phân công cho người kiểm tra khác. Trưởng đoàn/Quản lý có thể can thiệp khi cần.</div>':'')<div class="requirement-meta"><div><b>Thủ tục kiểm tra</b><p>'+esc(rq.test)+'</p></div><div><b>Bằng chứng kỳ vọng</b><p>'+esc(rq.expected)+'</p></div></div>'+UI.sectionHeader("Evidence workspace","Bằng chứng được quản lý theo revision; không ghi đè lịch sử.",canWork&&c.can("conduct_fieldwork",a)?'<button class="btn" data-act="upload">+ Upload bằng chứng</button>':"")+evidenceCards(c,ra)+(canWork&&c.can("conduct_fieldwork",a)?'<div class="drop evidence-drop" data-act="upload"><b>Thả hoặc chọn tệp bằng chứng</b><div class="small muted">Ảnh, PDF, chứng từ, screenshot…</div></div>':"")+'<div class="field"><label>Ghi nhận người kiểm tra</label><textarea id="obs" placeholder="Ghi nhận thực tế, dữ kiện hoặc điểm cần lưu ý...">'+esc(ra.observation||"")+'</textarea></div><div class="ai-panel">'+UI.sectionHeader("Đề xuất AI","Chỉ là proposal; luôn cần human review.",canWork&&c.can("review_ai",a)?'<button class="btn alt" data-act="analyze">Phân tích / đề xuất</button>':"")+(props.length?props.map(function(p){var conf=U().confidence(p.confidence);return'<div class="ai"><div class="row"><b>'+esc(c.lab(p.result))+'</b>'+(conf.pct!==null?'<span class="confidence-chip '+conf.tone+'">'+conf.pct+'% · '+conf.label+'</span>':"")+'</div><p class="small">'+esc(p.text)+'</p><div class="small muted">AI không xác nhận kết luận tuân thủ hoặc Phát hiện.</div>'+(p.status==="proposed"?'<div class="row"><button class="btn" data-accept="'+p.id+'">Chấp nhận đề xuất</button><button class="btn alt" data-reject="'+p.id+'">Bác bỏ</button></div>':tag(p.status))+'</div>'}).join(""):UI.empty("Chưa có đề xuất AI","Có thể chạy phân tích sau khi đã có dữ kiện/bằng chứng."))+'</div>'+(canWork&&c.can("conduct_fieldwork",a)?'<div class="row" style="margin-top:12px"><button class="btn" data-act="setResult">Ghi nhận kết quả</button>'+(c.can("confirm_finding",a)?'<button class="btn red" data-act="finding">Tạo Draft Phát hiện</button>':"")+'</div>':"")+'</div>':"";
    return hero+'<div class="row fieldwork-toolbar" style="margin-bottom:12px"><select id="asSel">'+c.visibleAssessments().map(function(x){return'<option value="'+x.id+'" '+(x.id===a.id?"selected":"")+'>'+esc(x.name)+'</option>'}).join("")+'</select>'+tag(a.status)+(a.lockedAt?'<span class="tag green">🔒 Phạm vi đã khóa</span>':'')+'</div>'+(!fieldworkActive?'<div class="note" style="margin-bottom:12px"><b>Fieldwork không hoạt động.</b> Cuộc đánh giá phải ở trạng thái <b>Đang kiểm tra</b> để ghi nhận kết quả, tải bằng chứng hoặc tạo phát hiện.</div>':'')+'<div class="split fieldwork-layout"><div class="stack">'+left+'</div>'+right+'</div>';
  };
})();