(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{},U=function(){return Screens.util};
  function timeline(c,f,responses){
    var esc=c.esc,fmt=U().fmtDate,status=f.status;
    var draftDone=true,responseDone=responses.length>0||["pending_final_review","final","closed","dismissed"].includes(status),finalDone=["final","closed","dismissed"].includes(status);
    var steps=[
      {name:"Draft Finding",done:draftDone,active:status==="draft"||status==="pending_unit_response",time:f.createdAt},
      {name:"Unit Response",done:responseDone,active:status==="pending_unit_response",time:responses[0]&&responses[0].at},
      {name:"Final Review",done:finalDone,active:status==="pending_final_review",time:f.finalizedAt||f.updatedAt},
      {name:status==="dismissed"?"Dismissed":"Final Finding",done:finalDone,active:status==="final",time:f.finalizedAt||f.updatedAt}
    ];
    return'<div class="finding-timeline">'+steps.map(function(s,i){return'<div class="timeline-step '+(s.done?"done ":"")+(s.active?"active":"")+'"><span class="timeline-dot">'+(s.done?"✓":i+1)+'</span><div><b>'+esc(s.name)+'</b><small>'+esc(s.time?fmt(s.time):(s.done?"Đã qua bước này":"Chưa thực hiện"))+'</small></div></div>'}).join("")+'</div>';
  }
  Screens.findings=function(c){
    var S=c.S,UI=c.UI,VM=c.VM,esc=c.esc,tag=c.tag,filt=c.filters||{};
    var fs=c.visibleFindings().filter(function(f){var q=String(filt.findingQuery||"").trim().toLowerCase();if(filt.findingStatusFilter&&filt.findingStatusFilter!=="all"&&f.status!==filt.findingStatusFilter)return false;if(filt.findingSeverityFilter&&filt.findingSeverityFilter!=="all"&&f.severity!==filt.findingSeverityFilter)return false;var ra=S.ra.find(function(x){return x.id===f.raId}),req=ra&&S.requirements.find(function(x){return x.id===ra.requirementId});return !q||[f.title,f.fact,f.criteria,f.gap,f.impact,f.rec,req&&req.code,req&&req.title].filter(Boolean).join(" ").toLowerCase().includes(q)});
    var vm=VM.findingSummary?VM.findingSummary(c.visibleFindings()):{open:0,high:0,pendingResponse:0,pendingFinal:0,final:0,closed:0};
    var hero=UI.pageIntro({eyebrow:"FINDING LIFECYCLE",title:"Phát hiện tuân thủ",description:"Draft Finding → Unit Response → Final Review → Final Finding. Timeline giúp nhìn rõ trạng thái và điểm đang chờ xử lý."});
    var summary=UI.metricGrid([{label:"Phát hiện mở",value:vm.open,tone:"warning"},{label:"Cao / nghiêm trọng",value:vm.high,tone:vm.high?"danger":"positive"},{label:"Chờ đơn vị phản hồi",value:vm.pendingResponse,tone:"warning"},{label:"Chờ chốt cuối",value:vm.pendingFinal,tone:"warning"},{label:"Đã chốt",value:vm.final,tone:"info"},{label:"Đã đóng / hủy",value:vm.closed,tone:"positive"}]);
    var controls='<div class="row product-toolbar" style="margin-bottom:12px"><input id="findingSearch" value="'+esc(filt.findingQuery||"")+'" placeholder="Tìm phát hiện..." style="min-width:250px"><select id="findingStatusFilter"><option value="all">Tất cả trạng thái</option>'+Array.from(new Set(S.findings.map(function(x){return x.status}))).map(function(s){return'<option value="'+esc(s)+'" '+(filt.findingStatusFilter===s?"selected":"")+'>'+esc(c.lab(s))+'</option>'}).join("")+'</select><select id="findingSeverityFilter"><option value="all">Tất cả mức độ</option>'+["low","medium","high","critical"].map(function(s){return'<option value="'+s+'" '+(filt.findingSeverityFilter===s?"selected":"")+'>'+s+'</option>'}).join("")+'</select><span class="small muted">'+fs.length+' kết quả</span></div>';
    var cards=fs.length?fs.map(function(f){var ra=S.ra.find(function(x){return x.id===f.raId}),q=ra&&S.requirements.find(function(x){return x.id===ra.requirementId}),resp=S.responses.filter(function(x){return x.findingId===f.id}),a=c.findingAssessment(f);return'<div class="card finding finding-v1"><div class="row"><div><b>'+esc(f.title)+'</b><div class="small muted">'+esc(q&&q.code)+' · '+esc(q&&q.title)+'</div></div><span class="right">'+tag(f.status)+' <span class="tag red">'+esc(f.severity)+'</span></span></div>'+timeline(c,f,resp)+'<div class="finding-facts"><div><b>Dữ kiện</b><p>'+esc(f.fact)+'</p></div><div><b>Tiêu chí</b><p>'+esc(f.criteria)+'</p></div><div><b>Khoảng cách</b><p>'+esc(f.gap)+'</p></div><div><b>Rủi ro/Tác động</b><p>'+esc(f.impact||"—")+'</p></div></div><div class="finding-response"><b class="small">Phản hồi đơn vị</b>'+(resp.length?resp.map(function(r){return'<div class="ai"><b>'+esc(r.type)+'</b><div class="small">'+esc(r.text)+'</div><div class="small muted">'+U().fmtDate(r.at)+'</div></div>'}).join(""):'<div class="small muted">Chưa có phản hồi.</div>')+'</div>'+(f.dispositionNote?'<div class="ai"><b>Nhận định chốt</b><div class="small">'+esc(f.dispositionNote)+'</div></div>':"")+'<div class="row finding-actions"><span class="small"><b>Khuyến nghị:</b> '+esc(f.rec||"—")+'</span>'+(f.status==="pending_unit_response"&&c.can("respond_finding",a)?'<button class="btn alt right" data-respond="'+f.id+'">Phản hồi</button>':"")+(f.status==="pending_final_review"&&c.can("confirm_finding",a)?'<button class="btn right" data-finalize="'+f.id+'">Chốt Phát hiện</button>':"")+(f.status==="final"&&c.can("assign_action",a)?'<button class="btn" data-actionfor="'+f.id+'">+ Giao hành động</button>':"")+'</div></div>'}).join(""):UI.empty("Chưa có phát hiện phù hợp","Điều chỉnh bộ lọc hoặc hoàn tất fieldwork để tạo Draft Finding.");
    return hero+summary+controls+cards;
  };
})();