(function(){
  var Screens=window.ComplianceScreens=window.ComplianceScreens||{};
  Screens.settings=function(c){
    var UI=c.UI,esc=c.esc,r=c.runtimeReadiness||{},ns=c.S.notificationSettings||{};
    var hero=UI.pageIntro({eyebrow:"ADMIN & OPERATIONS",title:"Cấu hình vận hành",description:"Quản lý thông báo, thành viên, readiness và các nguyên tắc chuyển production."});
    var notify='<div class="card"><h2>Thông báo & chuyển cấp</h2><div class="field"><label><input type="checkbox" id="setInApp" '+(ns.inApp!==false?"checked":"")+'> Bật thông báo trong ứng dụng</label></div><div class="field"><label><input type="checkbox" id="setOverdue" '+(ns.overdueEscalation!==false?"checked":"")+'> Chuyển cấp ngay khi hành động quá hạn</label></div><div class="field"><label>Nhắc trước hạn hành động (ngày)</label><input type="number" min="0" id="setReminderDays" value="'+esc(ns.reminderBeforeDueDays==null?"":ns.reminderBeforeDueDays)+'" placeholder="Để trống = không nhắc trước hạn"></div><button class="btn" data-act="saveNotifySettings">Lưu cấu hình</button><p class="small muted">Ngưỡng chỉ có hiệu lực khi được quản trị nhập; hệ thống không tự giả định.</p></div>';
    var readiness='<div class="card"><h2>Sẵn sàng Production</h2><div class="readiness"><div class="ready-cell"><b>Clerk Email Auth</b><div class="small">'+(r.auth&&r.auth.configured?"Đã cấu hình":"Chưa cấu hình")+'</div></div><div class="ready-cell"><b>Database</b><div class="small">'+(r.database&&r.database.configured?"Đã kết nối":"Chưa kết nối")+'</div></div><div class="ready-cell"><b>Private Blob</b><div class="small">'+(r.storage&&r.storage.configured?"Đã cấu hình":"Chưa cấu hình")+'</div></div><div class="ready-cell"><b>Schema chuẩn hóa</b><div class="small">'+(r.database&&r.database.normalizedReady?"Sẵn sàng":"Chưa migrate")+'</div></div><div class="ready-cell"><b>OCR</b><div class="small">'+(r.documentIntelligence&&r.documentIntelligence.ocrConfigured?"Đã cấu hình":"Adapter sẵn sàng")+'</div></div><div class="ready-cell"><b>AI Extraction</b><div class="small">'+(r.ai&&r.ai.configured?"Đã cấu hình":"Rule fallback")+'</div></div></div>'+(r.productionReady?'<div class="pass" style="margin-top:12px">Đủ điều kiện nền để chuyển production.</div>':'<div class="search-warning" style="margin-top:12px"><b>Còn thiếu:</b> '+esc((r.missing||[]).join(", ")||"Schema/database migration")+'</div>')+'<button class="btn alt" style="margin-top:12px" data-act="refreshReadiness">Kiểm tra lại</button></div>';
    var members=c.currentUser&&c.currentUser.role==="compliance_admin"?'<div class="card" style="margin-top:14px">'+UI.sectionHeader("Thành viên nội bộ","Cấp trước quyền theo email, vai trò và phạm vi đơn vị.",'<button class="btn" data-act="manageUsers">Quản lý thành viên</button>')+'</div>':"";
    return hero+'<div class="split">'+notify+readiness+'</div><div class="card" style="margin-top:14px"><h2>Nguyên tắc production</h2><ol class="small"><li>Shared database chỉ dùng sau khi Clerk xác minh danh tính.</li><li>Bằng chứng thật chỉ lưu ở private storage.</li><li>Phân quyền backend theo user + org scope; UI không phải control.</li><li>AI/OCR chỉ tạo proposal; nghĩa vụ pháp lý và Finding luôn cần human confirmation.</li></ol></div>'+members;
  };
})();