ssmentId);ra.complianceResult=p.proposedResult;ra.workflowStatus='in_review';}appendDecision(state,{objectType:'AIAnalysisProposal',objectId:p.id,decisionType:accept?'accept':'reject',reason:'Human review',actor:currentRole});persist();render();}

function setResult(result){const ra=raById(selectedRA);if(!ra||isLocked(ra.assessmentId))return;const prev=ra.complianceResult;ra.complianceResult=result;ra.workflowStatus='done';ra.assessedBy=currentRole;ra.assessedAt=nowIso();appendDecision(state,{objectType:'RequirementAssessment',objectId:ra.id,decisionType:'result_change',fromState:prev,toState:result,reason:'Kết quả do người đánh giá xác nhận',actor:currentRole});persist();render();}

function createFinding(){
  const ra=raById(selectedRA),q=ra&&requirement(ra.requirementId);if(!ra||!q||isLocked(ra.assessmentId))return;
  const evidenceCount=state.evidenceLinks.filter(l=>l.targetType==='RequirementAssessment'&&l.targetId===ra.id).length;
  modal(`<h2>Xác nhận Finding</h2><div class="note">Finding chính thức do con người xác nhận. Hiện có ${evidenceCount} evidence link; nếu không có file, phải mô tả rõ dữ kiện quan sát/phỏng vấn.</div><form id="findingForm"><div class="field"><label>Tiêu đề</label><input name="title" value="Không tuân thủ ${esc(q.code)}" required></div><div class="field"><label>Dữ kiện (Fact)</label><textarea name="fact" required>${esc(ra.observation||'')}</textarea></div><div class="field"><label>Tiêu chí (Criteria)</label><textarea name="criteria" required>${esc(q.title)}${q.sourceClause?` — ${esc(q.sourceClause)}`:''}</textarea></div><div class="field"><label>Khoảng cách/Vi phạm (Gap)</label><textarea name="gap" required></textarea></div><div class="field"><label>Nguyên nhân gốc (nếu đã xác định)</label><textarea name="rootCause"></textarea></div><div class="field"><label>Rủi ro/Tác động</label><textarea name="riskImpact"></textarea></div><div class="field"><label>Yêu cầu/Khuyến nghị</label><textarea name="recommendation"></textarea></div><div class="split"><div class="field"><label>Mức độ</label><select name="severity"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><div class="field"><label>Ưu tiên xử lý</label><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></div></div><button class="btn red">Xác nhận Finding</button></form>`);
  document.getElementById('findingForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.fact.trim()){alert('Finding phải có dữ kiện.');return;}const f={id:generateId('finding'),requirementAssessmentId:ra.id,...d,status:'confirmed',confirmedBy:currentRole,confirmedAt:nowIso()};state.findings.push(f);ra.complianceResult='non_compliant';ra.workflowStatus='done';ra.assessedBy=currentRole;ra.assessedAt=nowIso();appendDecision(state,{objectType:'Finding',objectId:f.id,decisionType:'confirm',reason:f.title,actor:currentRole});persist();closeModal();view='findings';render();};
}

function unitResponse(findingId){modal(`<h2>Phản hồi đơn vị</h2><form id="responseForm"><div class="field"><label>Loại phản hồi</label><select name="responseType"><option>Đồng ý</option><option>Không đồng ý</option><option>Bổ sung bằng chứng</option><option>Đề xuất điều chỉnh</option></select></div><div class="field"><label>Nội dung phản hồi</label><textarea name="responseText" required></textarea></div><button class="btn">Gửi phản hồi</button></form>`);document.getEle